# Usa a imagem oficial do Node
FROM node:20

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas os arquivos de dependência primeiro (cache inteligente)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta usada pelo React
EXPOSE 3000

# Comando para iniciar o app em modo dev
CMD ["npm", "start"]
